# Generated by Django 5.2.17 on 2026-10-06 08:46

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='vi', max_length=2, verbose_name='language')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='The URL: /blog/<slug>/. Filled in from the title; changing it later breaks old links.', max_length=120)),
                ('translation_key', models.SlugField(blank=True, help_text='Links the Vietnamese and English versions of the same article: give both the same value. Defaults to the slug.', max_length=120)),
                ('description', models.CharField(help_text='One or two sentences (ideally 70–160 characters). Shown in Google results, on the blog list and when the link is shared.', max_length=160)),
                ('body', models.TextField(help_text="Written in Markdown. Start sections at <code>## Heading</code> (the title is already the page's H1).\n<code>**bold**</code> · <code>*italic*</code> · <code>- list item</code> · <code>1. numbered</code> ·\n<code>[link text](https://...)</code> · <code>&gt; quote / tip box</code> · a blank line starts a new paragraph.")),
                ('cover', models.ImageField(blank=True, help_text='Optional. A wide image (about 1200×630) also becomes the Facebook/Zalo share picture.', upload_to='img/articles/')),
                ('cover_alt', models.CharField(blank=True, help_text='Describe the image in a few words, for Google and screen readers.', max_length=200, verbose_name='cover description')),
                ('author', models.CharField(default='Cross Tech Edu', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft (not on the website)'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateField(default=blog.models.today, verbose_name='publish date')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='last updated')),
            ],
            options={
                'ordering': ['-published_at', 'title'],
                'constraints': [models.UniqueConstraint(fields=('locale', 'slug'), name='unique_slug_per_locale')],
            },
        ),
    ]
